### ISSUE TITLE
Duplicated column name sortable

### ISSUE THREAD

**Issue by patrickvanharen** [PinkWhaleNL/Jellyfish#17]
While installing a fresh JF setup, the command php artisan migrate returns the error below.

 [Illuminate\Database\QueryException]
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'sortable' (SQL: alter table `jelly_types` a
  dd `sortable` int not null default '0')

  [PDOException]
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'sortable'

**Comment by paperclamp** [comment]
Fixed!
